services:
  automacao-python:
    build: .
    container_name: automacao-worker
    restart: always
    env_file:
      - .env
    environment:
      - TZ=America/Manaus
    networks:
      - evolutionapi_default # Nome da rede onde a Evolution está rodando

# Conecta a uma rede externa já existente (a rede da sua Evolution)
networks:
  evolutionapi_default: # Nome da rede externa
    external: true
